swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "frontend.endpoints.hello-11-3-22.cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.hello-11-3-22.cloud.goog"
  target: "35.190.93.28"
