apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-gmc-ingress
  annotations:
    networking.gke.io/managed-certificates: "gke-ingress-cert-01,gke-ingress-cert-02"
    kubernetes.io/ingress.global-static-ip-name: "ingress-ip"
spec:
  rules:
  - host: hello.endpoints.triggering-a-198-8487f60b.cloud.goog
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: my-mc-service
            port:
              number: 60001
  - host: luismendeze.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: my-mc-service
            port:
              number: 60002